### PR TITLE
Add checkbox to choose custom mode resolution

### PR DESCRIPTION
**Pull request by dydyamotya**
I've added a checkbox to use custom resolution. It is very useful, if you have Ultra wide monitor.
I've changed import of tools file, because otherwise it uses the system package.
I'm opened, if there are some mistakes, but for me it works like a charm.

### CODE REVIEW

**Review by nwg-piotr — COMMENTED** [review]
1. Changing the import results in:

```
$ nwg-displays
Traceback (most recent call last):
  File "/usr/bin/nwg-displays", line 33, in <module>
    sys.exit(load_entry_point('nwg-displays==0.1.3', 'gui_scripts', 'nwg-displays')())
  File "/usr/bin/nwg-displays", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/nwg_displays-0.1.3-py3.10.egg/nwg_displays/main.py", line 33, in <module>
    from tools import *
ModuleNotFoundError: No module named 'tools'
```

2. What's the purpose of this checkbox? Can't you just enter your desired width, height and refresh rate in the form? The "Modes" combo is a helper, not the only way to enter values.

**Comment by dydyamotya** [comment]
1. Opps, sorry, didn't test it through.Certainly, need to change it back in imports.
2. As I understand, one needs to add --custom flag to **mode** command to have it work like you expect. I tried to set custom resolution without --custom flag and nothing happened. Manually execution of command with --custom flag worked and I've decided to add "custom" checkbox. 
This PR added "custom" flag to sway https://github.com/swaywm/sway/pull/4675

**Comment by nwg-piotr** [comment]
I understand. If so, we can add the `--custom` flag, but place the checkbox in another place, please. I expect the form to fit horizontally in a half of full HD screen, so we have not enough space in the bottom row. I think we just need one more row below the one that contains 'Size', 'Refresh' and the 'Modes' combo.

**Comment by dydyamotya** [comment]
I've changed widgets position. Look, pls, if it fits your estimations.

**Comment by nwg-piotr** [comment]
Very well. I'll take a look when I'm back home. If I find the layout not yet ready, I'll correct it myself. I want nwg-displays , [nwg-shell-config](https://github.com/nwg-piotr/nwg-shell-config) and [nwg-look](https://github.com/nwg-piotr/nwg-look) to look similar.

**Comment by nwg-piotr** [comment]
main.py, line 470:

```python
item["active"], item["dpms"], item["adaptive_sync_status"], "disabled", item["focused"], item["monitor"]
```

The `form_custom_mode` check button value is not persistent between consecutive runs. It seems we can't get this value in the `list_outputs()` function, so it should be saved somewhere. I suggest a list of output names w/ custom mode turned on in the `config` dictionary, e.g. like this:

```json
{
  "view-scale": 0.15,
  "snap-threshold": 10,
  "indicator-timeout": 500,
  "custom-mode": ["HDMI-A-1", "DP-1"]
}
```

You could use it something like this:

```python
outputs = list_outputs()
    for key in outputs:
        item = outputs[key]
        custom_mode = key in config["custom-mode"]
        b = DisplayButton(key, item["description"], item["x"], item["y"], round(item["width"]), round(item["height"]),
                          item["transform"], item["scale"], item["scale_filter"], item["refresh"], item["modes"],
                          item["active"], item["dpms"], item["adaptive_sync_status"], custom_mode, item["focused"], item["monitor"])

```

Of course you'd also need to save config on the check button "toggled" event.

**Comment by dydyamotya** [comment]
Hi!
I've implemented config thing, check it out, please.

**Comment by nwg-piotr** [comment]
Great, thanks! I'll at my desk later tonight.

**Comment by nwg-piotr** [comment]
Definitely this not a feature for beginners, as it may potentially make brake ones sway configuration. Hope no one gets hurt.

**Comment by dydyamotya** [comment]
> Definitely this not a feature for beginners, as it may potentially brake ones sway configuration. Hope no one gets hurt.

Really? Why?
Nonetheless, you can't set up resolution on ultrawide monitors by another way. So, I think it is a nice feature)

**Comment by nwg-piotr** [comment]
> Really? Why?

I managed to crash sway with the `--custom` flag. Needed to edit `~/config/sway/outputs` in console.

> I think it is a nice feature

Indeed, thank you for the contribution. I added a tooltip to warn users that they need to think twice.

**Pull request merged**
